services:
  portainer:
    build:
      context: .
      dockerfile: Dockerfile_portainer
    container_name: portainer-app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 600M
    # command: https://gist.github.com/deviantony/62c009b41bde5e078b1a7de9f11f5e55
    restart: always
    ports:
      # Map host 9443 to container 9443 for HTTPS UI
      - 9443:9443
      # Keep 8000 for the agent/edge tunnel
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_portainer_data:/data
    # Command to launch Portainer with SSL enabled
    command: -p 9443 --ssl --sslcert /certs/portainer.crt --sslkey /certs/portainer.key
    networks:
      - net_portainer
networks:
  net_portainer:
    # is default
    # driver: bridge

volumes:
  vol_portainer_data:
